version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always
    networks:
    - esnet

  influxdb:
    image: influxdb:1.7
    environment:
        - INFLUXDB_USER=root
        - INFLUXDB_USER_PASSWORD=root
        - INFLUXDB_DB=home_db
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb2:/var/lib/influxdb
    restart: always
    links:
        - mosquitto
        - influxdb
    networks:
    - esnet

  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    restart: always
    links:
        - influxdb
    networks:
    - esnet

  mqttbridge:
    build: ./02-bridge
    image: gluteusmaximus/mqttbridge
    container_name: mqttbridge
    depends_on:
      - mosquitto
      - influxdb
    restart: always
    environment:
        - INFLUXDB_ADDRESS=influxdb
        - MOSQUITTO_ADDRESS=mosquitto
    links:
        - mosquitto
        - influxdb
    networks:
    - esnet

networks:
  esnet:

volumes:
  grafana:
    driver: local
  influxdb2:
    driver: local
  mosquitto_data:
    driver: local  
  mosquitto_log:
    driver: local      